# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Hint' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hint
  pod 'Bolts'
  pod "Crashlytics"
  pod "Fabric"
  pod 'Parse'
  
  target 'HintTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
